### ISSUE TITLE
Remove certificate validation prompts from generate_config.py script

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#117]
The prompts are still there in the generate_config.py script. The user should not be prompted for these settings.

Validate SSL certificates (default true) (Optional)
# 

Location of an ssl certificate bundle (If not set will use the bundle included with certifi instead) (Optional)

**Comment by element-82** [comment]
Julia,
to be clear, you don't want to see the following:

Validate SSL certificates (default true) (Optional)

Location of an ssl certificate bundle (If not set will use the bundle included with certifi instead) (Optional)

The defaults are sane, and you may not want to validate the certs, e.g. so that we can work with staging clouds.  We may not want to use the certifi CA bundle.  You might have your own.  So, not sure what you mean, please clarify.

**Comment by jkeffer** [comment]
My understanding is that users should never disable certificate validation. If so, they shouldn't see the prompt "Validate SSL certificates (default true) (Optional)". If we need to turn off validation for our own staging environment, we can add the entries manually.

Is the location of the certificate bundle separate from validation? If so, is this something we only need to do for a staging environment or is it something the user could legitimately change? If it is legitimate, you don't need to remove that prompt.

**Comment by element-82** [comment]
I think they are both legitimate.  I agree that we have to have strong defaults, but we should not enforce it.  They could always read the code and put in the value on their own.  E.g. services like apache allow you to disable validation.

**Comment by jkeffer** [comment]
I agree that we don't need to enforce it in the sense of removing the code that checks the settings. But we shouldn't prompt them for it. If they read the code, they can change the config file themselves. I can't recall if there is a setup script for Apache, but if you want to disable validation, you have to read the comments in the config file.
