### ISSUE TITLE
attributes.cfg parsed but auto attributes set to false

### ISSUE THREAD

**Issue by ccassidy-wrs** [Wind-River/device-cloud-python#123]
The application device-manager.py now parses file "attributes.cfg" for custom attributes and publishes them to the portal. However the default hdc_device_manager_def has autoDefAttrs = false, meaning new attributes cannot be published and return an error.

Need to change modify hdc_device_manager_def.cfg and set autoDefAttrs to true.

**Comment by element-82** [comment]
Chris,
the reason we keep our defaults to no auto is because everyone would add their own attributes and the consequence is that everyone would see everyone else's in the attributes tab.  It becomes a mess.  The work flow we want is to provide a sane default TD.  The customer run all our default apps.  If they want to change something, that is ok.  Clone the default and make changes.  We have to automation scripts for this in the share/admin-tools dir.  This should be documented.
Pb

**Comment by ccassidy-wrs** [comment]
For my usecase, I can simply modify the thing def in the customer's org to enable auto attributes, so this issue can be closed.
